### ISSUE TITLE
Make menu items fully customizable

### ISSUE THREAD

**Issue by i9hdkill** [BentoBoxWorld/ControlPanel#10]
#### Is your feature request related to a problem?

I really like GUIs, as they are more intuitive than commands. I had a look at controlpanel and tried to customize menuitems to my likings, but that didn't work out. I wasn't able to get the command out of the item title.

#### Describe the solution you'd like us to implement.

I would like to able to customize the item name, bound command and the lore.
Didn't try multiline lore, but that would be a nice feature aswell.

### Additional context

Possible outcome
![image](https://user-images.githubusercontent.com/4679374/80136881-9fc67100-85a2-11ea-9fc4-15ef3d5c80cd.png)

How settings could look like
![image](https://user-images.githubusercontent.com/4679374/80137170-2418f400-85a3-11ea-8a48-c4ece7e8e3e3.png)

**Comment by i9hdkill** [comment]
Thanks you very much!!!
Howevery, it still uses commands as items
https://github.com/BentoBoxWorld/ControlPanel/commit/a9237cbc9c616375cd0e59a8191c961b95f638e8#diff-4f7d341d6cdb3bc404d5ec92fa01db1dR93

**Comment by BONNe** [comment]
Hmm, did you re-import your control panels?
As contorlPanels.yml and controlPanelsTemplate.yml are just template files for importing :)

**Comment by i9hdkill** [comment]
Steps I did:
- deleted contorlPanels.yml
- redid our config entirely from scratch in controlPanelsTemplate.yml.
- bsb controlpanel import overwrite.

It imported correctly. When I set the command to the name, it shows the command as name ingame. However this obviously breaks the command.

**Comment by BONNe** [comment]
Yea, I found the issue :D
I forgot to add name reader from template file :D
