### ISSUE TITLE
Spawn mobs

### ISSUE THREAD

**Issue by 100petr** [BentoBoxWorld/ControlPanel#12]
How do I allow players to turn monsters on and off on their island?

**Comment by tastybento** [comment]
It's not to do with the Control Panel. Players can use `/is settings`, then pick the Island Settings and Expert page and enable disable monster spawning there:
<img width="546" alt="Screen Shot 2020-05-20 at 10 21 05 PM" src="https://user-images.githubusercontent.com/4407265/82526261-67a24780-9ae8-11ea-949a-3108782e8d95.png">
