### ISSUE TITLE
Not possible to override or delete the CP

### ISSUE THREAD

**Issue by Redstylt** [BentoBoxWorld/ControlPanel#13]
#### Describe the bug
I imported the default CP but after i made few changement (like comment the biomes section) than i ran the cmd : /bsbadmin controlpanel import but it said 0 controlpanel imported and it's still the default one.

Could also be good to have more cmd like _/is controlpanel delete_ and _/is controlpanel list_

Paper MC 1.15.2 #372
Bentobox v1.31.1
CP V 1.7.0

**Comment by BONNe** [comment]
./bsb controlpanel import reimport

It will be improved in future :)
