### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/ControlPanel#24]
### Expected behavior

When I clicked on the icons in the menu, I expected the commands to work.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/47111280/148254031-36a33996-e28f-44b7-92d6-06634ef2b7ae.png)
It was working normally but I guess it broke after upgrading to 1.18.1. I have no complete knowledge of the subject. But when I click it, it gives these errors in the console and nothing happened.

I think it's related to this issue. #19 

### Steps/models to reproduce

Try clicking on the items in the menu and executing the commands.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/148254672-22558814-126b-42c5-8f76-408253d3dba9.png)

**Comment by OverBrave** [comment]
What exactly is the problem?

**Comment by BONNe** [comment]
Hmm, I cannot reproduce this issue.
Could you share files that are located in: `/plugins/bentobox/database/ControlPanelObject`?

**Comment by OverBrave** [comment]
> Hmm, I cannot reproduce this issue. Could you share files that are located in: `/plugins/bentobox/database/ControlPanelObject`?

[BSkyBlock_default.zip](https://github.com/BentoBoxWorld/ControlPanel/files/7912776/BSkyBlock_default.zip)

**Comment by BONNe** [comment]
Hmm, I am still not able to reproduce even with your config.

may be players does not have permission to run these commands?

**Comment by OverBrave** [comment]
I can't even use it myself. I have all the permissions. :D You are trying in version 1.18.1 right?

**Comment by BONNe** [comment]
![screenshot-bentobox-version](https://user-images.githubusercontent.com/1344358/150518711-de46d830-8c43-44fa-8562-e1130fbb74cc.png)

**Comment by BONNe** [comment]
ControlPanel 1.13.1 contains only locales changes, so it may not affect.
BetoBox 1.20 does not contain any changes to the command calls. At least I do not know about them, if they exists.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/150542535-ced105bb-2471-4698-afd6-fe0c967e9373.png)
I don't understand, why is it happening?

At the same time, it sends an unknown command warning in the game.

**Comment by BONNe** [comment]
Well, the admin command starts with `[server]`

But in general, I have no idea what could cause that. Maybe a server engine. What exactly do you use and which version?

And do you have the custom command "aliases" for commands?

**Comment by OverBrave** [comment]
If you're talking about server software, I'm using Pufferfish Build 38.
And no.

**Comment by BONNe** [comment]
Well, that is weird, I tried with the same build and everything works correctly. 

I am out of ideas why it may not work.

If you try something that is not "bentobox" command, like "balance", "home", "spawn". 
Do they work?

**Comment by OverBrave** [comment]
Yes, working. Only bentobox commands not working.

**Comment by BONNe** [comment]
Hmm,
And do the commands work if you replace `[label]` with GameModePlayer command?

**Comment by OverBrave** [comment]
No.

**Comment by BONNe** [comment]
@tastybento do you have ideas?

**Comment by tastybento** [comment]
I need to study this - I'm sorry, I will have a tough time looking at it during the week due to work IRL. But I will look at it when I can.

**Comment by OverBrave** [comment]
> Hmm, And do the commands work if you replace `[label]` with GameModePlayer command?

I didn't want to extra open issue about this.
I think the command problem is also in the "Gamemode type" selection menu of the "challenges" addon.

When click button on menu, said "Unknown command."

**Comment by BONNe** [comment]
Can you share your plugin list?

**Comment by BONNe** [comment]
Control Panel is very simple in its nature. 
It just uses simple command call: `Player.performCommand(<command>)`

If the issue is with a plugin, then, most likely, it is either overwriting NMS `Player.performCommand(<command>)` and then the developer is doing something wrongly, or it is canceling `PlayerCommandPreprocessEvent`.

There is nothing BentoBox can do in both situations. However, it is very weird, that plugin would cancel commands from other plugins. 
You should report it to the plugin developer, as he should not cancel commands, that do not belong to him.

Unless, that is a point of that plugin, and it probably is a plugin configuration thing.

**Comment by OverBrave** [comment]
This problem fixed by Gcore developer.
