### ISSUE TITLE
Port the  "usecontrolpanel config" of askyblock to bentobox

### ISSUE THREAD

**Issue by xion87** [BentoBoxWorld/ControlPanel#7]
I would like to see this setting again, was pretty usefull:

    Use the control panel as the default display for /island
    /island will always create an island if one does not exist
    If the control panel is not used, then /island will teleport the player home
    Players can change this setting using /island cp on or /island cp off
    usecontrolpanel: true

Doing /is, will create the island and doing it again will open the panel, and it allow to use /is subcommands too,
Many players of my bskblock are misisng this, i tried to use some workround, but is not better.

**Comment by BONNe** [comment]
Currently not possible due to BentoBox limitation.
https://github.com/BentoBoxWorld/BentoBox/issues/498

In any case, this will not be controlled from ControlPanel side, but from BentoBox.
